services:
  postgres:
    image: postgres:latest
    container_name: postgres-fagord
    environment:
      POSTGRES_PASSWORD: db_secret
      POSTGRES_USER: db_user
      POSTGRES_DB: db_fagord
    ports:
      - "5432:5432"
    volumes:
      - ./db_persistent_storage:/var/lib/postgresql/data